# Generated by Django 5.2.5 on 2025-10-24 21:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Назва події')),
                ('description', models.TextField(verbose_name='Опис події')),
                ('short_description', models.CharField(blank=True, max_length=300, verbose_name='Короткий опис')),
                ('event_type', models.CharField(choices=[('concert', 'Концерт'), ('festival', 'Фестиваль'), ('exhibition', 'Виставка'), ('master_class', 'Майстер-клас'), ('competition', 'Конкурс'), ('lecture', 'Лекція'), ('children', 'Дитяча подія'), ('other', 'Інше')], max_length=20, verbose_name='Тип події')),
                ('start_date', models.DateTimeField(verbose_name='Дата та час початку')),
                ('end_date', models.DateTimeField(blank=True, null=True, verbose_name='Дата та час завершення')),
                ('location', models.CharField(max_length=200, verbose_name='Місце проведення')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=8, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Ціна')),
                ('max_participants', models.PositiveIntegerField(blank=True, null=True, verbose_name='Максимальна кількість учасників')),
                ('current_participants', models.PositiveIntegerField(default=0, verbose_name='Поточна кількість учасників')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна подія')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Показувати на головній')),
                ('image', models.ImageField(blank=True, upload_to='events/', verbose_name='Зображення')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Подія',
                'verbose_name_plural': 'Події',
                'ordering': ['-start_date'],
                'indexes': [models.Index(fields=['start_date', 'is_active'], name='events_even_start_d_06f960_idx'), models.Index(fields=['is_featured', 'is_active'], name='events_even_is_feat_2a0b22_idx')],
            },
        ),
    ]
