# Generated by Django 5.2.5 on 2025-10-24 21:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Collective',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Назва колективу')),
                ('collective_type', models.CharField(choices=[('dance', 'Танцювальний'), ('music', 'Музичний'), ('theater', 'Театральний'), ('art', 'Художній'), ('craft', 'Рукоділля'), ('sport', 'Спортивний'), ('other', 'Інший')], max_length=20, verbose_name='Тип колективу')),
                ('age_group', models.CharField(choices=[('children', 'Діти (3-6 років)'), ('kids', 'Діти (7-12 років)'), ('teens', 'Підлітки (13-17 років)'), ('adults', 'Дорослі (18+)'), ('seniors', 'Літні люди (60+)'), ('all', 'Всі вікові групи')], max_length=20, verbose_name='Вікова група')),
                ('description', models.TextField(verbose_name='Опис колективу')),
                ('short_description', models.CharField(blank=True, max_length=300, verbose_name='Короткий опис')),
                ('leader', models.CharField(max_length=100, verbose_name='Керівник')),
                ('leader_photo', models.ImageField(blank=True, upload_to='collectives/leaders/', verbose_name='Фото керівника')),
                ('leader_description', models.TextField(blank=True, verbose_name='Про керівника')),
                ('schedule', models.TextField(verbose_name='Розклад занять')),
                ('price_per_month', models.DecimalField(decimal_places=2, default=0, max_digits=8, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Вартість на місяць')),
                ('max_members', models.PositiveIntegerField(blank=True, null=True, verbose_name='Максимальна кількість учасників')),
                ('current_members', models.PositiveIntegerField(default=0, verbose_name='Поточна кількість учасників')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активний набір')),
                ('image', models.ImageField(blank=True, upload_to='collectives/', verbose_name='Зображення')),
                ('youtube_url', models.URLField(blank=True, verbose_name='YouTube посилання')),
                ('rating', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)], verbose_name='Рейтинг')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Колектив',
                'verbose_name_plural': 'Колективи',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['collective_type', 'is_active'], name='collectives_collect_5154c6_idx'), models.Index(fields=['age_group', 'is_active'], name='collectives_age_gro_69f2e2_idx')],
            },
        ),
    ]
