# Generated by Django 5.2.5 on 2025-10-25 09:44

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collectives', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CollectiveRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('child_name', models.CharField(max_length=100, verbose_name="Ім'я дитини/учасника")),
                ('child_age', models.PositiveIntegerField(verbose_name='Вік учасника')),
                ('parent_name', models.CharField(max_length=100, verbose_name="Ім'я батька/опікуна")),
                ('phone', models.CharField(max_length=17, validators=[django.core.validators.RegexValidator(message="Номер телефону має бути в форматі: '+380501234567'", regex='^\\+?1?\\d{9,15}$')], verbose_name='Номер телефону')),
                ('email', models.EmailField(max_length=254, verbose_name='Email адреса')),
                ('notes', models.TextField(blank=True, verbose_name='Додаткові нотатки')),
                ('status', models.CharField(choices=[('pending', 'Очікує розгляду'), ('approved', 'Підтверджено'), ('rejected', 'Відхилено')], default='pending', max_length=10, verbose_name='Статус заявки')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('collective', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='collectives.collective', verbose_name='Гурток')),
            ],
            options={
                'verbose_name': 'Заявка до гуртка',
                'verbose_name_plural': 'Заявки до гуртків',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_name', models.CharField(max_length=100, verbose_name="Ім'я автора")),
                ('rating', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Рейтинг')),
                ('content', models.TextField(verbose_name='Відгук')),
                ('is_approved', models.BooleanField(default=False, verbose_name='Опубліковано')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('collective', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='collectives.collective', verbose_name='Гурток')),
            ],
            options={
                'verbose_name': 'Відгук',
                'verbose_name_plural': 'Відгуки',
                'ordering': ['-created_at'],
            },
        ),
    ]
