# Generated by Django 5.2.5 on 2025-11-14 10:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collectives', '0002_collectiveregistration_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collective',
            name='age_group',
            field=models.CharField(choices=[('children', 'Діти (4-10 років)'), ('kids', 'Діти (4-17 років)'), ('teens', 'Діти (5-17 років)'), ('adults', 'Дорослі (18+)'), ('seniors', 'Літні люди (60+)'), ('all', 'Всі вікові групи')], max_length=20, verbose_name='Вікова група'),
        ),
        migrations.AlterField(
            model_name='collective',
            name='collective_type',
            field=models.CharField(choices=[('dance', 'Танцювальний'), ('music', 'Музичний'), ('theater', 'Театральний'), ('other', 'Інший')], max_length=20, verbose_name='Тип колективу'),
        ),
        migrations.AlterField(
            model_name='collective',
            name='current_members',
            field=models.PositiveIntegerField(blank=True, verbose_name='Поточна кількість учасників'),
        ),
        migrations.AlterField(
            model_name='collective',
            name='price_per_month',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=8, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Вартість на місяць'),
        ),
    ]
