# Generated by Django 5.2.5 on 2025-11-14 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collectives', '0003_alter_collective_age_group_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collective',
            name='current_members',
        ),
        migrations.RemoveField(
            model_name='collective',
            name='max_members',
        ),
        migrations.RemoveField(
            model_name='collective',
            name='price_per_month',
        ),
    ]
