# Generated by Django 5.2.5 on 2025-10-25 10:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactFormSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name="Ім'я")),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Телефон')),
                ('subject', models.CharField(max_length=200, verbose_name='Тема')),
                ('message', models.TextField(verbose_name='Повідомлення')),
                ('is_processed', models.BooleanField(default=False, verbose_name='Оброблено')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': "Заявка зворотного зв'язку",
                'verbose_name_plural': "Заявки зворотного зв'язку",
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ContactInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.TextField(verbose_name='Адреса')),
                ('phone', models.CharField(max_length=20, verbose_name='Телефон')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('work_hours', models.TextField(verbose_name='Години роботи')),
                ('map_embed_code', models.TextField(blank=True, help_text='HTML код для вставки карти Google Maps', verbose_name='Код для вставки карти')),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Широта')),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Довгота')),
                ('facebook_url', models.URLField(blank=True, verbose_name='Facebook')),
                ('instagram_url', models.URLField(blank=True, verbose_name='Instagram')),
                ('youtube_url', models.URLField(blank=True, verbose_name='YouTube')),
                ('telegram_url', models.URLField(blank=True, verbose_name='Telegram')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Контактна інформація',
                'verbose_name_plural': 'Контактна інформація',
            },
        ),
        migrations.CreateModel(
            name='HistoryTimeline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField(verbose_name='Рік')),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок події')),
                ('description', models.TextField(verbose_name='Опис події')),
                ('image', models.ImageField(blank=True, upload_to='history/', verbose_name='Зображення')),
                ('is_important', models.BooleanField(default=False, verbose_name='Важлива подія')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок відображення')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Подія історії',
                'verbose_name_plural': 'Події історії',
                'ordering': ['-year', 'order'],
            },
        ),
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name="Ім'я та прізвище")),
                ('position', models.CharField(choices=[('director', 'Директор'), ('deputy_director', 'Заступник директора'), ('manager', 'Керівник відділу'), ('teacher', 'Педагог'), ('administrator', 'Адміністратор'), ('other', 'Інший співробітник')], max_length=20, verbose_name='Посада')),
                ('short_position', models.CharField(blank=True, max_length=100, verbose_name='Посада (коротко)')),
                ('bio', models.TextField(verbose_name='Біографія')),
                ('short_bio', models.CharField(blank=True, max_length=200, verbose_name='Коротка біографія')),
                ('photo', models.ImageField(blank=True, upload_to='team/', verbose_name='Фото')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('phone', models.CharField(blank=True, max_length=17, validators=[django.core.validators.RegexValidator(message="Номер телефону має бути в форматі: '+380501234567'", regex='^\\+?1?\\d{9,15}$')], verbose_name='Номер телефону')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок відображення')),
                ('is_active', models.BooleanField(default=True, verbose_name='Працює')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Співробітник',
                'verbose_name_plural': 'Співробітники',
                'ordering': ['order', 'name'],
            },
        ),
    ]
