# Generated by Django 5.2.5 on 2025-11-12 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teammember',
            name='position',
            field=models.CharField(choices=[('director', 'Директор'), ('teacher', 'Педагог'), ('specialist', 'Інструктор'), ('staff', 'Персонал'), ('other', 'Інший співробітник')], max_length=20, verbose_name='Посада'),
        ),
    ]
