# Generated by Django 5.2.5 on 2025-11-13 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0002_alter_teammember_position'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historytimeline',
            options={'ordering': ['year', '-order'], 'verbose_name': 'Подія історії', 'verbose_name_plural': 'Події історії'},
        ),
    ]
