# Generated by Django 5.2.5 on 2025-11-13 19:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0003_alter_historytimeline_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Назва посади')),
                ('department', models.CharField(choices=[('director', 'Директор'), ('creative', 'Творчий відділ'), ('technical', 'Технічний відділ')], max_length=20, verbose_name='Відділ')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок відображення')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
            ],
            options={
                'verbose_name': 'Посада',
                'verbose_name_plural': 'Посади',
                'ordering': ['department', 'order', 'name'],
            },
        ),
        migrations.AlterModelOptions(
            name='teammember',
            options={'ordering': ['position__department', 'order', 'name'], 'verbose_name': 'Співробітник', 'verbose_name_plural': 'Співробітники'},
        ),
        migrations.RemoveField(
            model_name='teammember',
            name='short_position',
        ),
        migrations.AddField(
            model_name='teammember',
            name='slug',
            field=models.SlugField(blank=True, unique=True, verbose_name='URL-адреса'),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='position',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_members', to='about.position', verbose_name='Посада'),
        ),
    ]
