# Generated by Django 5.2.5 on 2025-11-13 19:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0004_position_alter_teammember_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='teammember',
            name='nickname',
            field=models.CharField(default=-7200, max_length=100, verbose_name='Нікнейм'),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='slug',
            field=models.SlugField(blank=True, default=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_members', to='about.position', verbose_name='Посада'), unique=True, verbose_name='Slug to URL'),
        ),
    ]
