# Generated by Django 5.2.5 on 2025-11-13 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0005_teammember_nickname_alter_teammember_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='position',
            name='department',
            field=models.CharField(choices=[('director', 'Керівництво'), ('creative', 'Творчий відділ'), ('technical', 'Технічний відділ')], max_length=20, verbose_name='Відділ'),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='slug',
            field=models.SlugField(blank=True, unique=True, verbose_name='Slug to URL'),
        ),
    ]
