# Generated by Django 5.2.5 on 2025-11-13 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0006_alter_position_department_alter_teammember_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teammember',
            name='short_bio',
            field=models.CharField(blank=True, max_length=350, verbose_name='Коротка біографія'),
        ),
    ]
